const menu = [
  {
    id: 1,
    title: "eggs and bacon",
    category: "breakfast",
    price: 10.99,
    img: "./images/jaja.jpg",
    desc: `Eggs and bacon as simple as that, is the best combination for breakfast of every southern american family.. `,
  },
  {
    id: 2,
    title: "Paprikash",
    category: "lunch",
    price: 16.99,
    img: "./images/paprikash.jpg",
    desc: `Simple yet satisfying, chicken paprikash is a Hungarian recipe made with chicken browned in butter and cooked with onions and paprika, then finished with a little sour cream mixed in. Serve over dumplings or noodles.`,
  },
  {
    id: 3,
    title: "Salty caramel shake",
    category: "shakes",
    price: 6.99,
    img: "./images/karamel.jpg",
    desc: ` Salted Caramel shake is made with creamy vanilla ice cream and homemade salted caramel sauce. Topped with fluffy whipped cream, extra salted caramel sauce and toffee bits — this is the perfect chilly drink to indulge in this summer! `,
  },
  {
    id: 4,
    title: "Šopska salata",
    category: "breakfast",
    price: 8.99,
    img: "./images/sopska.jpg",
    desc: `This colourful dish is similar to a Greek salad, minus the olives. Its a fresh, flavourful accompaniment to the abundance of meat dishes served at a Serbian feast. `,
  },
  {
    id: 5,
    title: "ćevapi",
    category: "lunch",
    price: 22.99,
    img: "./images/cevapi.jpg",
    desc: `Cevapi are easy to make, grilled sausages from Southeastern Europe that burst with smoky flavor and are perfect for serving with flatbread and sliced onions. `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 16.99,
    img: "./images/item-6.jpeg",
    desc: `Oreo Milkshake Recipe - A super easy milkshake made with vanilla ice cream, milk, and Oreo cookies!  This sweet treat is a hit with the whole family on a hot day!`,
  },
  {
    id: 7,
    title: "burek",
    category: "breakfast",
    price: 8.99,
    img: "./images/burek.jpg",
    desc: `Burek is the food you eat for breakfast, lunch, dinner, or just as a snack. It’s not exactly very healthy, but on the upside, if you eat a big slice of burek, it is sure to fill you. That way, you can skip your next meal. `,
  },
  {
    id: 8,
    title: "pilav",
    category: "lunch",
    price: 14.99,
    img: "./images/pilav.jpg",
    desc: `Plov is the most classic dish of Uzbekistan, consisting of rice, onion, carrots and meat, all cooked slowly in layers in a traditional cast-iron kazan (essentially, a cauldron). `,
  },
  {
    id: 9,
    title: "Plazma Shake",
    category: "shakes",
    price: 11.99,
    img: "./images/plazma.jpg",
    desc: `A shake made of pieces of Plazma cookies and milk with whipped cream on top.  `,
  },
];
export default menu;
